baseURL = ""
languageCode = "fr-fr"
title = "Polytech MTP BDE"
theme = "hugo-theme-learn"

[params]
themeVariant = "blue"
author = "Florent HUGOUVIEUX"
description = "Documentation for BDE website of Polytech Montpellier"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe = true